/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cc.hutunotes.farmerljx.jnidemo.jni;

public class JniTest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JniTest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JniTest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigdemo4jJNI.delete_JniTest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JniTest(double[] data, int len) {
    this(swigdemo4jJNI.new_JniTest(data, len), true);
  }

  public double getVal(int index) {
    return swigdemo4jJNI.JniTest_getVal(swigCPtr, this, index);
  }

  public int jniTestAlgo(int p1) {
    return swigdemo4jJNI.JniTest_jniTestAlgo(swigCPtr, this, p1);
  }

}
