/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cc.hutunotes.farmerljx.jnidemo.jni;

public class swigdemo4jJNI {
  public final static native long new_JniTest(double[] jarg1, int jarg2);
  public final static native double JniTest_getVal(long jarg1, JniTest jarg1_, int jarg2);
  public final static native int JniTest_jniTestAlgo(long jarg1, JniTest jarg1_, int jarg2);
  public final static native void delete_JniTest(long jarg1);
}
